package version

// Constraint enables matching a version based on lower and upper bounds.
type Constraint struct {
	Gt  *Version // Greater than...
	Gte *Version // Greater than or equal to...
	Lt  *Version // Less than...
	Lte *Version // Less than or equal to...
}
